create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  company text,
  email text,
  status text not null default 'New',
  value numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.cases (
  id bigint generated by default as identity primary key,
  case_number text unique not null,
  customer text not null,
  title text not null,
  priority text not null default 'Medium',
  status text not null default 'Open',
  created_at timestamptz not null default now()
);
create table if not exists public.campaigns (
  id bigint generated by default as identity primary key,
  name text not null,
  audience integer not null default 0,
  status text not null default 'Draft',
  responses integer not null default 0,
  created_at timestamptz not null default now()
);
alter table public.leads enable row level security;
alter table public.cases enable row level security;
alter table public.campaigns enable row level security;
